### ISSUE TITLE
minecraft crash

### ISSUE THREAD

**Issue by Thunderrock424242** [Povstalec/StellarView#1]
[crash-2023-07-18_17.43.47-client.txt](https://github.com/Povstalec/StellarView/files/12089257/crash-2023-07-18_17.43.47-client.txt)

**Comment by Thunderrock424242** [comment]
Version 1.20.1 forge

**Comment by Povstalec** [comment]
Seems to be a problem that has something to do with Iris shaders, which, given my current lack of knowledge on how shaders work, I don't know how to fix.

**Comment by Thunderrock424242** [comment]
I think it may be fixed since your latest update
