### ISSUE TITLE
[SUGGESTION] Change Venus' Texture.

### ISSUE THREAD

**Issue by Noobly-Walker** [Povstalec/StellarView#13]
The current texture appears to be of Venus' surface. When we see Venus in the sky however, we don't see its surface. Venus' surface is almost entirely obscured by heavy cloud cover.
![14SCI-VENUS1-alt-videoSixteenByNine3000](https://github.com/Povstalec/StellarView/assets/59349202/0743b169-55a0-4f43-a88d-ab776ef158d0)

Altering the texture should also make it more visually distinct from Mars.

**Comment by Noobly-Walker** [comment]
![venus](https://github.com/Povstalec/StellarView/assets/59349202/c87a9656-bac9-47de-a7ee-bce4a7d9b19f)

**Comment by Noobly-Walker** [comment]
I'm just gonna do it myself. It's not that hard to change some pixels.

**Comment by Povstalec** [comment]
Actually a pretty cool idea

**Comment by Noobly-Walker** [comment]
This may have already been solved due to merging my pull request.
