### ISSUE TITLE
Clientside crash

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Povstalec/StellarView#27]
1.20.1 latest version, forge.

https://pastebin.com/maZA2kxZ

**Comment by Povstalec** [comment]
Seems like the same problem with Oculus as this one
https://github.com/Povstalec/StellarView/issues/26

**Comment by MaxWasUnavailable** [comment]
o7, good to close / lock then. Will report any further findings there (though I doubt I'll have any beyond this crash)
