### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Thunderrock424242** [Povstalec/StellarView#3]
Add more colors to the sky right now it's just white dots which is nice but the sky could use more.

**Comment by Povstalec** [comment]
By more colors do you mean colored stars or some background colors?

**Comment by Noobly-Walker** [comment]
Why not both?
But I think they specifically meant colored stars, based on how they mentioned "white dots".

**Comment by Noobly-Walker** [comment]
this has been finished, and can be closed
