### ISSUE TITLE
pretty sure thats a missing texture in the centere of a galaxy

### ISSUE THREAD

**Issue by koostcrashed** [Povstalec/StellarView#41]
minecraft 1.20.1
stellar view 0.3.1
stargate journey 0.6.32
**Describe the bug**
i think there is a missing texture
![image](https://github.com/user-attachments/assets/bdac27d0-70cb-46db-aaed-2d4abe4c272e)
i havnt checked yet if it is a conflict with another mod.

**To Reproduce**
look at the sky and zoom in at this galaxy (im sorry i dont have the name at hand)

**Comment by Noobly-Walker** [comment]
assets\sgjourney\stellarview\celestials\star\pegasus\lantea_system: points to assets/stellarview/stellarview/textures/environment/star/orange_star.png, but file was moved to assets/stellarview/stellarview/textures/environment/star/template/orange_star.png
