### ISSUE TITLE
[BUG] High times on the game's clock cause celestial objects to jitter.

### ISSUE THREAD

**Issue by Noobly-Walker** [Povstalec/StellarView#6]
I set the in-game clock to 17,721,480,000 (2023 in-game years), and due to floating point imprecision or something like that, the moon and stars are unable to move smoothly across the sky.

I have no clue why exactly this would be. If I were to hazard a guess, the rotation of the various layers of the skybox (?) takes the in-game timer and does math to it to determine degrees/radians/whatever, but rather than modulo'd into the bounds of 0 to 360/6.283/whatever, it is unbounded. As with many things however, I'm likely wrong.

**Comment by Povstalec** [comment]
Sounds like a float problem, I'll try to take a look at what's causing it

**Comment by Povstalec** [comment]
Fixed, I guess? At least it should be harder to notice now.

**Comment by Noobly-Walker** [comment]
> You do not have permissions to reopen this issue.
But I made this issue.
@Frametimed Make a new issue, I guess?

**Comment by Povstalec** [comment]
It's okay, I fixed it again.
